    <header>
        <h3>Description</h3>
    </header>
    <p>Magento has an ingenious way to provde you with a drop-down list of available countries and a linked state/provice selector. Unfortunately Magento does not include the provinces for Belgium. This small update will provide you with the provinces for Belgium, the package comes with several locales listed below</p>
    <p>Import and enhance your customer experience with just a few clicks</p>
    <p>
        Supported locales are
        <ul>
            <li>en_US</li>
            <li>en_GB</li>
            <li>nl_NL</li>
            <li>nl_BE</li>
            <li>fr_FR</li>
            <li>fr_CH</li>
            <li>fr_LU</li>
            <li>fr_LI</li>
            <li>fr_AT</li>
            <li>it_IT</li>
            <li>it_CH</li>
        </ul>
    </p>
