<header>
    <h3>Images</h3>
</header>
<div class="box alt" id="gallery">
    <div class="row 50% uniform">
        <div class="4u work-item">
            <a href="/images/magento/modules/katai-belgium-local-in-checkout/full/checkout_de_de.png" class="image fit">
                <img src="/images/magento/modules/katai-belgium-local-in-checkout/thumb/checkout_de_de.png" title="logo katai locale de_DE checkout" />
            </a>
        </div>
        <div class="4u work-item">
            <a href="/images/magento/modules/katai-belgium-local-in-checkout/full/checkout_fr_fr.png" class="image fit">
                <img src="/images/magento/modules/katai-belgium-local-in-checkout/thumb/checkout_fr_fr.png" title="logo katai locale fr_FR checkout" />
            </a>
        </div>
    </div>
</div>