<!-- Two -->
<section id="module">
    <header>
        <h2>Katai Belgium province selection in checkout</h2>
        <p>Version 1.0.0.0</p>
    </header>
    <?php echo $this->insert('modules::katai-belgium-local-in-checkout/description'); ?>

    <?php echo $this->insert('modules::katai-belgium-local-in-checkout/images'); ?>

    <?php echo $this->insert('modules::katai-belgium-local-in-checkout/installation'); ?>


    <?php echo $this->insert('modules::shared/disclaimer'); ?>

    <?php echo $this->insert('modules::shared/support'); ?>

    <ul class="actions">
        <li><a href="/katai-belgium-local-in-checkout" target="_parent" class="button frame">More Info</a></li>
        <li><a href="https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=722KDK6U3GFY8" class="button" onclick="_gaq.push(['_trackEvent', 'product', 'buy', 'katai-belgium-local-in-checkout', 1]);"><i class="icon fa-cc-paypal"></i> Buy &euro; 5</a></li>
        <li><a href="/" class="button" target="_parent">Back</a></li>
    </ul>
</section>