<!-- Two -->
<section id="two">
    <header>
        <h2>Katai Ekomi Product Review integration</h2>
        <p>Version <version>1.2.1.12</version></p>
    </header>
    <?php echo $this->insert('modules::katai-ekomi/description'); ?>

    <?php echo $this->insert('modules::katai-ekomi/installation'); ?>

    <?php echo $this->insert('modules::shared/disclaimer'); ?>

    <?php echo $this->insert('modules::shared/support'); ?>

    <ul class="actions">
        <li><a href="/katai-ekomi" target="_parent" class="button frame">More Info</a></li>
        <li><a href="https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=NUGWUZAHPVD8N" class="button" onclick="_gaq.push(['_trackEvent', 'product', 'buy', 'katai-ekomi', 1]);"><i class="icon fa-cc-paypal"></i> Buy &euro; 10</a></li>
        <li><a href="/" class="button" target="_parent">Back</a></li>
    </ul>
</section>