<!-- Two -->
<section id="two">
    <header>
        <h2>Katai Geolocate Checkout</h2>
        <p>Version <version>1.1.0.0</version></p>
    </header>
    <?php echo $this->insert('modules::katai-geolocatecheckout/description'); ?>

    <?php echo $this->insert('modules::katai-geolocatecheckout/images'); ?>

    <?php echo $this->insert('modules::katai-geolocatecheckout/installation'); ?>

    <?php echo $this->insert('modules::shared/disclaimer'); ?>

    <?php echo $this->insert('modules::shared/support'); ?>

    <ul class="actions">
        <li><a href="/katai-geolocatecheckout" target="_parent" class="button frame">More Info</a></li>
        <li><a href="https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=XYMT6JTXYMUPG" class="button" onclick="_gaq.push(['_trackEvent', 'product', 'buy', 'katai-geolocatecheckout', 1]);"><i class="icon fa-cc-paypal"></i> Buy &euro; 30</a></li>
        <li><a href="/" class="button" target="_parent">Back</a></li>
    </ul>
</section>