<!-- Two -->
<section id="module">
    <header>
        <h2>Katai CSS/JavaScript Merge version</h2>
        <p>Version 1.0.0.1</p>
    </header>
    <?php echo $this->insert('modules::katai-css-js-merge-version/description'); ?>

    <?php echo $this->insert('modules::katai-css-js-merge-version/images'); ?>

    <?php echo $this->insert('modules::katai-css-js-merge-version/installation'); ?>


    <?php echo $this->insert('modules::shared/disclaimer'); ?>

    <?php echo $this->insert('modules::shared/support'); ?>

    <ul class="actions">
        <li><a href="/katai-css-js-merge-version" target="_parent" class="button frame">More Info</a></li>
        <li><a href="https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=QQECYG8X9BK8Q" class="button"><i class="icon fa-cc-paypal"></i> Buy &euro; 10</a></li>
        <li><a href="/" class="button" target="_parent">Back</a></li>
    </ul>
</section>