<section id="two">
    <h2>Recent Release Magento Modules</h2>
    <div class="row">
        <article class="3u 12u$(xsmall) work-item">
            <a href="/katai-css-js-merge-version" class="image fit thumb"  data-poptrox="ignore">
                <img src="/images/magento/modules/katai-css-js-merge-version/thumb/logo-katai-merge.png" title="logo katai merge" /></a>
            <h3>Katai CSS/JavaScript Merge</h3>
            <version>1.0.0.1</version>
            <p>Mark your Merged JS/CSS to a fixed point, this will ensure your Varnish powered shop cache will be able to serve correct CSS/JS after a deploy until caches are expired naturally.</p>
            <p>Ideally for high traffic websites</p>
        </article>
        <article class="3u 12u$(xsmall) work-item">
            <a href="/katai-ekomi" class="image fit thumb"  data-poptrox="ignore">
                <img src="/images/magento/modules/katai-ekomi/thumb/logo-katai-ekomi.png" title="katai ekomi integration" /></a>
            </a>
            <h3>Katai Ekomi Product Review integration</h3>
            <version>1.2.1.12</version>
            <p>Integrate Ekomi Product reviews into you Magento store.</p>
        </article>
<!--        <article class="3u$ 12u$(xsmall) work-item">-->
<!--            <a href="images/fulls/03.jpg" class="image fit thumb"><img src="/images/thumbs/03.jpg" alt="" /></a>-->
<!--            <h3>Tortor metus commodo</h3>-->
<!--            <p>Lorem ipsum dolor sit amet nisl sed nullam feugiat.</p>-->
<!--        </article>-->
<!--        <article class="3u 12u$(xsmall) work-item">-->
<!--            <a href="images/fulls/04.jpg" class="image fit thumb"><img src="images/thumbs/04.jpg" alt="" /></a>-->
<!--            <h3>Quam neque phasellus</h3>-->
<!--            <p>Lorem ipsum dolor sit amet nisl sed nullam feugiat.</p>-->
<!--        </article>-->
<!--        <article class="3u 12u$(xsmall) work-item">-->
<!--            <a href="images/fulls/05.jpg" class="image fit thumb"><img src="images/thumbs/05.jpg" alt="" /></a>-->
<!--            <h3>Nunc enim commodo aliquet</h3>-->
<!--            <p>Lorem ipsum dolor sit amet nisl sed nullam feugiat.</p>-->
<!--        </article>-->
<!--        <article class="3u$ 12u$(xsmall) work-item">-->
<!--            <a href="images/fulls/06.jpg" class="image fit thumb"><img src="images/thumbs/06.jpg" alt="" /></a>-->
<!--            <h3>Risus ornare lacinia</h3>-->
<!--            <p>Lorem ipsum dolor sit amet nisl sed nullam feugiat.</p>-->
<!--        </article>-->
    </div>
    <ul class="actions">
<!--        <li><a href="#" class="button">Full Portfolio</a></li>-->
    </ul>
</section>