<footer id="footer">
    <ul class="icons">
        <li><a href="http://www.twitter.com/mitchvdl" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
        <li><a href="http://www.facebook.com/mitchvdl" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
        <li><a href="http://www.github.com/mitchvdl" class="icon fa-github"><span class="label">Github</span></a></li>
        <li><a href="http://www.linkedin.com/in/mitchvdl" class="icon fa-linkedin"><span class="label">Linkedin</span></a></li>
        <li><a href="mailto:&#105;&#110;&#102;&#111;&#064;&#109;&#105;&#116;&#099;&#104;&#118;&#100;&#108;&#046;&#098;&#101;" class="icon fa-envelope-o"><span class="label">Email</span></a></li>
    </ul>
    <ul class="copyright">
        <li>&copy; 2015 mitchvdl.be</li>
        <li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
    </ul>
</footer>