<section id="one" class="frame">
    <header class="major">
        <h2>Professional Profile</h2>
    </header>
    <p>I'm a Magento Certified Developer, driven to help get the best out of a Magento installation; customisation and modular development are one of my main goals and objectives. Buidling the module that can be reused will not only benefit a consumer, but will decrease the time needed to implement it in a different solution.
        Grab the chances in life and face the challenges, each step brings you closer to your own success! Driven to efficiently learn new development techniques and technologies.</p>
    <ul class="actions">
        <!--<li><a href="#" class="button">Learn More</a></li>-->
    </ul>
</section>