<div class="table-wrapper">
    <table>
        <thead>
        <tr>
            <th>Certification</th>
            <th>URL</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>Magento Developer</td>
            <td><a href="http://www.magentocommerce.com/certification/directory/dev/176011/" alt="certification mitch vanderlinden" rel="nofollow" target="_blank">Magento Certification</a> <i class="icon fa-external-link"></i></td>
        </tr>
            </tbody>
        <tfoot>

        </tfoot>
    </table>
</div>