<div class="table-wrapper">
    <table>
        <thead>
        <tr>
            <th>Language</th>
            <th>Proficiency</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>Dutch</td>
            <td>Native / Bilingual</td>
        </tr>

        <tr>
            <td>English</td>
            <td>Native / Bilingual</td>
        </tr>
        <tr>
            <td>French</td>
            <td>Basic</td>
        </tr>
        <tr>
            <td>German</td>
            <td>Basic</td>
        </tr>
        <tr>
            <td>Czech</td>
            <td>Notes</td>
        </tr>

        </tbody>
        <tfoot>

        </tfoot>
    </table>
</div>