<div class="table-wrapper">
    <table>
        <thead>
        <tr>
            <th>Skill</th>
            <th>Proficiency</th>
            <th>Skill</th>
            <th>Proficiency</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>Magento</td>
            <td>ADVANCED, 4 YEARS</td>
            <td>PHP</td>
            <td>EXPERT, 7 YEARS</td>
        </tr>

        <tr>
            <td>MySQL</td>
            <td>EXPERT, 7 YEARS</td>
            <td>XHTML & CSS</td>
            <td>ADVANCED, 5 YEARS</td>
        </tr>

        <tr>
            <td>Javascript</td>
            <td>ADVANCED, 5 YEARS</td>
            <td>jQuery Framework</td>
            <td>ADVANCED, 5 YEARS</td>
        </tr>

        <tr>
            <td>jQuery Framework</td>
            <td>ADVANCED, 5 YEARS</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
        </tr>

        </tbody>
        <tfoot>

        </tfoot>
    </table>
</div>