<section id="one">
    <header class="major">
        <h2>Curriculum Vitae</h2>
        <h3>Work Experience summary</h3>
    </header>
</section>

<?php echo $this->insert('body::cv/workexperience/gide'); ?>
<?php echo $this->insert('body::cv/workexperience/summit'); ?>
<?php echo $this->insert('body::cv/workexperience/otys'); ?>
<?php echo $this->insert('body::cv/workexperience/phpro'); ?>
<?php echo $this->insert('body::cv/workexperience/base'); ?>


<section>
    <ul class="actions">
        <li><a href="/cv" class="button" target="_parent">Back</a></li>
    </ul>
</section>






