<section>
    <header>
        <h4 class="cvtitle">Temporary - Sales Representative / Jul 2009</h4>
    </header>
    <h5>KPNGroupBelgium (BASE), Maasmechelen, Belgium</h5>
    <div class="item">
        <ul>
            <li>Handeling invoices and repairs</li>
            <li>Stock counting</li>
            <li>Troubleshooting and solving</li>
            <li>Retail of Mobilephones, tarif plans and pre-paid</li>
        </ul>
    </div>
</section>
