<section>
    <header>
        <h4 class="cvtitle">Senior Magento Developer / Senior PHP Developer / Jun 2015 - Current</h4>
    </header>
    <h5>Geschenkidee D&amp;a GmbH, Berlin, Germany (<a href="http://www.geschenkidee.de/" alt="geschenkidee d&amp;a gmbh" rel="nofollow" target="_blank">link</a> <i class="icon fa-external-link"></i> )</h5>
    <div class="item">
        <ul>
            <li>Magento Developer Certified <a href="http://www.magentocommerce.com/certification/directory/dev/176011/" alt="certification mitch vanderlinden" rel="nofollow" target="_blank">Magento Certification</a> <i class="icon fa-external-link"></i> </li>
            <li>Magento framework</li>
            <li>Inhouse development and bug fixed for Magento projects</li>
            <li>Setting up live development environments based on VAGRANT</li>
        </ul>
    </div>
</section>