
<section>
    <header>
        <h4 class="cvtitle">Internship - Support and research / Mar 2012 - Dec 2012</h4>
    </header>
    <h5>OTYS Czech Republic, Prague, The Czech Republic (<a href="http://www.otys.cz" alt="otys cz" rel="nofollow" target="_blank">link</a> <i class="icon fa-external-link"></i> )</h5>
    <div class="item">
        <ul>
            <li>Research and development on the GWT platform</li>
            <li>second and thirdline support employee, solving and tracking bugs</li>
        </ul>
    </div>
</section>