<section>
    <header>
        <h4 class="cvtitle">Temporary - Performance tester / Jul 2011</h4>
    </header>
    <h5>PHPro, Antwerp, Belgium (<a href="http://www.phpro.be" alt="phpro" rel="nofollow" target="_blank">link</a> <i class="icon fa-external-link"></i> )</h5>
    <div class="item">
        <ul>
            <li>Peformance testing Magento Webshops through AB and JMeter</li>
            <li>Datamining and processing</li>
        </ul>
    </div>
</section>