<section>
    <header>
        <h4 class="cvtitle">Magento/PHP Developer / Jan 2013 - Jun 2015</h4>
    </header>
    <h5>Summit Media, Prague, The Czech Republic (<a href="http://www.summit.co.uk/" alt="summit media" rel="nofollow" target="_blank">link</a> <i class="icon fa-external-link"></i> )</h5>
    <div class="item">
        <ul>
            <li>Magento Developer Certified <a href="http://www.magentocommerce.com/certification/directory/dev/176011/" alt="certification mitch vanderlinden" rel="nofollow">Magento Certification</a> <i class="icon fa-external-link"></i></li>
            <li>Research and development on the <a href="http://www.vagrantup.com/" alt="vagrant documentation" rel="nofollow" target="_blank">VAGRANT</a> and PUPPET platform <i class="icon fa-external-link"></i></li>
            <li>Setting up live development environments based on VAGRANT</li>
            <li>Magento framework</li>
            <li>Inhouse development and bug fixed for various Magento projects, retail, automotive, cosmetics</li>
        </ul>
    </div>
</section>