<header>
    <h3>Disclaimer</h3>
</header>
<p>The Magento extension is provided as is, we're not reliable for any downtimes or malfunctions during the installation of the module, it is at all times adviced to create a back-up of your store (source code, databases) before proceeding with any module upgrade/installment.</p>
<p>Testing of a new module should happen on an enclosed environment to see the direct impact before replicating the behaviour on a production environment</p>
