<section id="one">
    <h2>Get In Touch</h2>
    <p>In case you have an issue with the module, reference your PayPal order number in the message.</p>
    <div class="row">
        <div class="8u 12u$(small)">
            <form method="post" action="mailto:&#105;&#110;&#102;&#111;&#064;&#109;&#105;&#116;&#099;&#104;&#118;&#100;&#108;&#046;&#098;&#101;" enctype="text/plain">
                <div class="row uniform 50%">
                    <div class="6u 12u$(xsmall)"><input type="text" name="name" id="name" placeholder="Name" /></div>
                    <div class="6u$ 12u$(xsmall)"><input type="email" name="email" id="email" placeholder="Email" /></div>
                    <div class="12u$"><textarea name="message" id="message" placeholder="Message" rows="4"></textarea></div>
                </div>

            <ul class="actions">
                <li><input type="submit" value="Send Message" /></li>
            </ul>
            </form>
        </div>
        <div class="4u$ 12u$(small)">
            <ul class="labeled-icons">
<!--                <li>-->
<!--                    <h3 class="icon fa-home"><span class="label">Address</span></h3>-->
<!--                    1234 Somewhere Rd.<br />-->
<!--                    Nashville, TN 00000<br />-->
<!--                    United States-->
<!--                </li>-->
<!--                <li>-->
<!--                    <h3 class="icon fa-mobile"><span class="label">Phone</span></h3>-->
<!--                    000-000-0000-->
<!--                </li>-->
                <li>
                    <h3 class="icon fa-envelope-o"><span class="label">Email</span></h3>
                    <a href="#">&#105;&#110;&#102;&#111;&#064;&#109;&#105;&#116;&#099;&#104;&#118;&#100;&#108;&#046;&#098;&#101;</a>
                </li>
            </ul>
        </div>
    </div>
</section>