<section>
    <header class="major">
        <h2>Curriculum Vitae / Work Experience</h2>
    </header>
    <p><?php echo $this->insert('body::cv/workexperience/gide'); ?></p>

    <ul class="actions">
        <li><a href="/cv/work-experience" class="button">View More</a></li>
    </ul>
</section>

<section>
    <header class="major">
        <h2>Certifications</h2>
    </header>
    <p><?php echo $this->insert('body::cv/certification'); ?></p>

    <ul class="actions">
<!--        <li><a href="/cv/education" class="button">View More</a></li>-->
    </ul>
</section>

<section>
    <header class="major">
        <h2>Technical Skills</h2>
    </header>
    <p><?php echo $this->insert('body::cv/technicalskill'); ?></p>

    <ul class="actions">
<!--        <li><a href="/cv/education" class="button">View More</a></li>-->
    </ul>
</section>

<section>
    <header class="major">
        <h2>Language Skills</h2>
    </header>
    <p><?php echo $this->insert('body::cv/languageskills'); ?></p>

    <ul class="actions">
<!--        <li><a href="/cv/education" class="button">View More</a></li>-->
    </ul>
</section>

<!---->
<!--<section>-->
<!--    <header class="major">-->
<!--        <h2>Education</h2>-->
<!--    </header>-->
<!--    <p>--><?php //echo $this->insert('body::cv/education/phl'); ?><!--</p>-->
<!---->
<!--    <ul class="actions">-->
<!--        <li><a href="/cv/education" class="button">View More</a></li>-->
<!--    </ul>-->
<!--</section>-->
<!---->
