    <header>
        <h3>Description</h3>
    </header>
    <p>This module will geolocate your customer checkout experience, this extension will try to estimate your customer address and pre-fill this in to the checkout. <br />
       The goal of the module is to enhance the customer experience and the time the user spends in the checkut by pre-filling their address. Having a pre-filled address will
       reduce the error that could happen by a user filling in the wrong address. </p>
