<header>
    <h3>Images</h3>
</header>
<div class="box alt" id="gallery">
    <div class="row 50% uniform">
        <div class="4u work-item">
            <a href="/images/magento/modules/katai-geolocatecheckout/katai-geocheckout.png" class="image fit">
                <img src="/images/magento/modules/katai-geolocatecheckout/katai-geocheckout.png" title="logo katai geocheckout main logo" />
            </a>
        </div>
        <div class="4u work-item">
            <a href="/images/magento/modules/katai-geolocatecheckout/full/be_1.png" class="image fit">
                <img src="/images/magento/modules/katai-geolocatecheckout/thumb/be_1.png" title="katai geocheckout backend configuration default installation" />
            </a>
        </div>
        <div class="4u$ work-item">
            <a href="/images/magento/modules/katai-geolocatecheckout/full/be_2_custom_msg.png" class="image fit">
                <img src="/images/magento/modules/katai-geolocatecheckout/thumb/be_2_custom_msg.png" title="katai geocheckout backend configuration custom installation" />
            </a>
        </div>
        <div class="4u work-item">
            <a href="/images/magento/modules/katai-geolocatecheckout/full/fe_custom_msg.png" class="image fit">
                <img src="/images/magento/modules/katai-geolocatecheckout/thumb/fe_custom_msg.png" title="katai geocheckout frontend custom message display" />
            </a>
        </div>
        <div class="4u work-item">
            <a href="/images/magento/modules/katai-geolocatecheckout/full/fe_default_agreement.png" class="image fit">
                <img src="/images/magento/modules/katai-geolocatecheckout/thumb/fe_default_agreement.png" title="katai geocheckout frontend default agreement message display" />
            </a>
        </div>
        <div class="4u$ work-item">
            <a href="/images/magento/modules/katai-geolocatecheckout/full/fe_address_resolve.png" class="image fit">
                <img src="/images/magento/modules/katai-geolocatecheckout/thumb/fe_address_resolve.png" title="katai geocheckout froendend address resolve" />
            </a>
        </div>
    </div>
</div>