    <header>
        <h3>Description</h3>
    </header>
    <p>When you're runnig a high traffic website with Vanish it is not advisable/encouraged to clear any type of cache, implementing a merged CSS/JS version will allow you to specify a structured point of for your Merged Javascript and CSS files.</p>
    <p>This specific point (value free to choose) will help your rollback procedure easier, a simple change in the back-end will help you generate new values on deploy to be used and stored by your Varnish caching.</p>
