<header>
    <h3>Images</h3>
</header>
<div class="box alt" id="gallery">
    <div class="row 50% uniform">
        <div class="4u work-item">
            <a href="/images/magento/modules/katai-css-js-merge-version/full/logo-katai-merge.png" class="image fit">
                <img src="/images/magento/modules/katai-css-js-merge-version/thumb/logo-katai-merge.png" title="logo katai merge" />
            </a>
        </div>
        <div class="4u work-item">
            <a href="/images/magento/modules/katai-css-js-merge-version/full/be_advanced_developer_merge.png" class="image fit">
                <img src="/images/magento/modules/katai-css-js-merge-version/thumb/be_advanced_developer_merge.png" title="Magento Backend Configuration Advanced Developer Merging configuration" />
            </a>
        </div>
        <div class="4u$ work-item">
            <a href="/images/magento/modules/katai-css-js-merge-version/full/fe_merged_version.png" class="image fit">
                <img src="/images/magento/modules/katai-css-js-merge-version/thumb/fe_merged_version.png" title="Frontend Magento merged version number" />
            </a>
        </div>
    </div>
</div>